In [33]:
import numpy as np
import pandas as pd
import h5py
import scipy.sparse as sps
from datetime import timedelta
# pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.options.display.max_columns = None
pd.options.display.max_rows = 100
pd.options.display.min_rows = 50
pd.options.display.precision = 2
pd.options.display.expand_frame_repr = True


In [34]:
filename = '../data/all_hourly_data.h5'

In [35]:
with h5py.File(filename, "r") as f:
    print("Keys: %s" % f.keys())


Keys: <KeysViewHDF5 ['codes', 'interventions', 'patients', 'vitals_labs', 'vitals_labs_mean']>


In [36]:
patients = pd.read_hdf(filename, key="patients")

one_hot = pd.get_dummies(patients[["gender", "admission_type", "first_careunit"]])
patients = patients.join(one_hot)
#display(patients.columns)

# include only patients with 6h < los < 600h or same for los_icu, but los_icu is in days
LOS_LOWER_THRESH = 6 #exclude if LOS is shorter than this many hours
LOS_UPPER_THRESH = 600 #exclude if LOS is longer than this many hours
patients["los"] = (patients["dischtime"] - patients["admittime"])
patients = patients[((patients["los"] > timedelta(hours=LOS_LOWER_THRESH))  & (patients["los"] < timedelta(hours=LOS_UPPER_THRESH))) | 
                    ((patients["los_icu"] * 24 > LOS_LOWER_THRESH)            & (patients["los_icu"] * 24 < LOS_UPPER_THRESH))]

MIN_AGE_THRESH = 18
patients = patients[patients["age"] > MIN_AGE_THRESH]

# ignore following dummies, common practice to exclude 1 dummy per category
# gender_M
# admission_type_ELECTIVE
# first_careunit_CCU

patients = patients[["age", "gender_F", "admission_type_EMERGENCY", "admission_type_URGENT", "first_careunit_CSRU", "first_careunit_MICU", "first_careunit_SICU", "first_careunit_TSICU"]]
print(patients.shape)
display(patients.head())


(37543, 8)


age  gender_F  admission_type_EMERGENCY  \
subject_id hadm_id icustay_id                                             
3          145834  211552     76.53         0                         1   
4          185777  294638     47.85         1                         1   
6          107064  228232     65.94         1                         0   
9          150750  220597     41.79         0                         1   
11         194540  229441     50.15         1                         1   

                               admission_type_URGENT  first_careunit_CSRU  \
subject_id hadm_id icustay_id                                               
3          145834  211552                          0                    0   
4          185777  294638                          0                    0   
6          107064  228232                          0                    0   
9          150750  220597                          0                    0   
11         194540  229441                          0                    0   

                               first_careunit_MICU  first_careunit_SICU  \
subject_id hadm_id icustay_id                                             
3          145834  211552                        1                    0   
4          185777  294638                        1                    0   
6          107064  228232                        0                    1   
9          150750  220597                        1                    0   
11         194540  229441                        0                    1   

                               first_careunit_TSICU  
subject_id hadm_id icustay_id                        
3          145834  211552                         0  
4          185777  294638                         0  
6          107064  228232                         0  
9          150750  220597                         0  
11         194540  229441                         0

In [37]:
interventions = pd.read_hdf(filename, key="interventions")
interventions["vasopressor"] = interventions[['vaso', 'vasopressin']].any(axis='columns').astype(int)
interventions = interventions[["vasopressor"]]
print(interventions.shape)
display(interventions.head())

(3183638, 1)


vasopressor
subject_id hadm_id icustay_id hours_in             
3          145834  211552     0                   0
                              1                   1
                              2                   1
                              3                   1
                              4                   1

In [38]:
# exclude patients that get vasopressor in the first 6h e.g. 0-5
excluded_subject_ids = interventions[interventions.index.get_level_values("hours_in").isin(range(6)) & interventions["vasopressor"] == 1]
excluded_subject_ids = excluded_subject_ids.index.get_level_values("subject_id").unique()
excluded_subject_ids.shape

(8406,)

In [39]:
outcome = pd.DataFrame(interventions.groupby(["subject_id", "hadm_id", "icustay_id"])["vasopressor"].agg("max"))
print(outcome.shape)
display(outcome.head())


(37543, 1)


vasopressor
subject_id hadm_id icustay_id             
3          145834  211552                1
4          185777  294638                0
6          107064  228232                0
9          150750  220597                1
11         194540  229441                0

In [40]:
vitals_labs_mean = pd.read_hdf(filename, key="vitals_labs_mean")

# Paper name -> df name
# map (mean arterial pressure) -> pulmonary artery pressure mean
# spontaneousrr (spontaneous respiratory rate) -> respiratory rate
# urine (urine output) -> not found! :/
# alt (alanine transaminase) -> alanine aminotransferase
# ast (aspartate aminotransferase) -> asparate aminotransferase
# inr (international normalised ratio) -> prothrombin time inr
mask = vitals_labs_mean.columns.get_level_values("LEVEL2").isin(["diastolic blood pressure", "fraction inspired oxygen", "glascow coma scale total", "heart rate", 
                                                                 "pulmonary artery pressure mean", "systolic blood pressure", "respiratory rate", "oxygen saturation",
                                                                 "temperature", "urine output", "blood urea nitrogen", "magnesium", "platelets", "sodium", "alanine aminotransferase",
                                                                 "hematocrit", "partial pressure of oxygen", "asparate aminotransferase", "potassium", "white blood cell count",
                                                                 "bicarbonate", "creatinine", "lactate", "partial pressure of carbon dioxide", "glucose", "prothrombin time inr",
                                                                 "hemoglobin", "bilirubin"])

#display(vitals_labs_mean.columns[vitals_labs_mean.columns.get_level_values("LEVEL2").str.contains("rate")]) # search column names
vitals_labs_mean = vitals_labs_mean.iloc[:, mask]
vitals_labs_mean = vitals_labs_mean[~vitals_labs_mean.index.get_level_values("subject_id").isin(excluded_subject_ids)]

print(vitals_labs_mean.shape)
display(vitals_labs_mean.head(10))


(2368063, 27)


LEVEL2                                 alanine aminotransferase  \
Aggregation Function                                       mean   
subject_id hadm_id icustay_id hours_in                            
4          185777  294638     0                             NaN   
                              1                             NaN   
                              2                             NaN   
                              3                             NaN   
                              4                             NaN   
                              5                           24.00   
                              6                             NaN   
                              7                             NaN   
                              8                             NaN   
                              9                             NaN   

LEVEL2                                 asparate aminotransferase bicarbonate  \
Aggregation Function                                        mean        mean   
subject_id hadm_id icustay_id hours_in                                         
4          185777  294638     0                              NaN         NaN   
                              1                              NaN         NaN   
                              2                              NaN         NaN   
                              3                              NaN         NaN   
                              4                              NaN         NaN   
                              5                            64.00       21.00   
                              6                              NaN         NaN   
                              7                              NaN         NaN   
                              8                              NaN         NaN   
                              9                              NaN         NaN   

LEVEL2                                 bilirubin blood urea nitrogen  \
Aggregation Function                        mean                mean   
subject_id hadm_id icustay_id hours_in                                 
4          185777  294638     0              NaN                 NaN   
                              1              NaN                 NaN   
                              2              NaN                 NaN   
                              3              NaN                 NaN   
                              4              NaN                 NaN   
                              5             1.52               10.00   
                              6              NaN                 NaN   
                              7              NaN                 NaN   
                              8              NaN                 NaN   
                              9              NaN                 NaN   

LEVEL2                                 creatinine diastolic blood pressure  \
Aggregation Function                         mean                     mean   
subject_id hadm_id icustay_id hours_in                                       
4          185777  294638     0               NaN                      NaN   
                              1               NaN                    63.00   
                              2               NaN                      NaN   
                              3               NaN                    57.00   
                              4               NaN                    61.00   
                              5              0.50                      NaN   
                              6               NaN                    55.00   
                              7               NaN                    58.00   
                              8               NaN                    56.00   
                              9               NaN                    60.00   

LEVEL2                                 fraction inspired oxygen  \
Aggregation Function                                       mean   
s

In [41]:
# FORMAT TO TENSOR (N x V x T)
subject_ids = vitals_labs_mean.index.get_level_values("subject_id").unique()

N = subject_ids.size
V = vitals_labs_mean.shape[1]
T = 6

#TODO use only first 6 hours -> can be replaced by last 6h or random sampling, method not indicated in paper
vitals_labs_mean = vitals_labs_mean[vitals_labs_mean.index.get_level_values("hours_in").isin(range(6))]

# fill 3d array
tensor = np.zeros((N, V, T))
for index, row in vitals_labs_mean.iterrows():
    # display(index)
    # display(row.shape)
    subject_id = index[0]
    hours_in = index[3]
    N_index = subject_ids.get_loc(subject_id)    # map id to index
    
    tensor[N_index, :, hours_in] = row

vitals_labs_mean = tensor
print(vitals_labs_mean.shape)
display(vitals_labs_mean[0,:,0])


(29137, 27, 6)


array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
       32. , 10.5,  2.1,  nan, 94. , 28. ,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan])

In [42]:
# indicators = pd.DataFrame(~vitals_labs_mean.isna())
indicators = ~np.isnan(vitals_labs_mean)
print(indicators.shape)
display(indicators[0,:,0])


(29137, 27, 6)


array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False])

In [44]:
vitals_labs_mean = np.nan_to_num(vitals_labs_mean, nan=0.0)
print(vitals_labs_mean.shape)
display(vitals_labs_mean[0,:,0])


(29137, 27, 6)


array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
       32. , 10.5,  2.1,  0. , 94. , 28. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ])

In [45]:
print(f"Exclude {excluded_subject_ids.size} patients...")

patients = patients[~patients.index.get_level_values("subject_id").isin(excluded_subject_ids)]
print(patients.shape)

outcome = outcome[~outcome.index.get_level_values("subject_id").isin(excluded_subject_ids)]
print(outcome.shape)

# vitals_labs_mean = vitals_labs_mean[~vitals_labs_mean.index.get_level_values("subject_id").isin(excluded_subject_ids)]
print(vitals_labs_mean.shape)

# indicators = indicators[~indicators.index.get_level_values("subject_id").isin(excluded_subject_ids)]
print(indicators.shape)

Exclude 8406 patients...
(29137, 8)
(29137, 1)
(29137, 27, 6)
(29137, 27, 6)
